### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by Brebinator** [bradcfisher/OctoPrint-ExcludeRegionPlugin#36] opened 2020-05-01 05:42 UTC
Ocotoprint will no longer support previous versions of python in the near future, it would be awesome if this plugin could get updated to be compatible with python 3.6.

**Comment by MrPaulAR** [comment] 2020-05-12 14:02
Duplicate of #32

**Comment by bradcfisher** [comment] 2020-06-11 01:54
Thanks for the report.  I haven't had much time for side projects lately, but I'll try to work through the updates needed to ensure Python 3 compatibility soon.  Since Python 3 support is already requested under #32, I'll close this report as a dup.

**Closed by bradcfisher** 2020-06-11 01:54 UTC
