### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by j-snijder** [bradcfisher/OctoPrint-ExcludeRegionPlugin#72] opened 2022-12-08 13:14 UTC
Update will not install and fails

**Comment by dojohnso** [comment] 2022-12-08 16:05
just for reference, this is a dupe report of https://github.com/bradcfisher/OctoPrint-ExcludeRegionPlugin/issues/71

**Comment by bradcfisher** [comment] 2022-12-09 01:37
Apologies for the issues.  There was some confusion with the plugin which caused version 0.3.1 to be released from a different location.  Anyone who had updated to that version may run into problems installing the new version 0.3.2.

All that should be needed to resolve the problem is to uninstall the plugin and reinstall a clean copy.

**Comment by bradcfisher** [comment] 2022-12-09 01:42
Closing as duplicate of #71

**Closed as completed by bradcfisher** 2022-12-09 01:42 UTC
Labels: duplicate
