### ISSUE TITLE
python 3.7 compatibility or newer environment

### ISSUE THREAD

**Issue by Greathouse2005** [bradcfisher/OctoPrint-ExcludeRegionPlugin#42] opened 2020-08-18 15:35 UTC
can we get the python updated to atleast 3.7 maybe 4? this has quit working on my new pi4 8gb. works great on my older install on my 4gb

**Comment by Hypertoken** [comment] 2020-09-16 19:47
Duplicate of #32

**Comment by bradcfisher** [comment] 2020-11-17 14:12
A new version 0.3.0 with Python 3 support has been released

**Closed by bradcfisher** 2020-11-17 14:12 UTC
